[package]
name = "openai-api-rs"
version = "0.1.10"
edition = "2021"
authors = ["Dongri Jin <dongrify@gmail.com>"]
license = "MIT"
description = "OpenAI API client library for Rust (unofficial)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.97"
